import grpc
from concurrent import futures
from autogenerated import services_pb2
from autogenerated import services_pb2_grpc


class NotificationService(
    services_pb2_grpc.NotificationServiceServicer
):
    def SendLoginNotification(self, request, context):
        print("📩 NotificationService received request")
        print(f"   user_id: {request.user_id}")
        print(f"   username: {request.username}")

        # simulate work
        response = services_pb2.ServiceResponse(
            success=True,
            message="Login notification sent"
        )

        print("📩 NotificationService sending response")
        print(f"   {response}\n")

        return response


server = grpc.server(futures.ThreadPoolExecutor(max_workers=5))
services_pb2_grpc.add_NotificationServiceServicer_to_server(
    NotificationService(), server
)

server.add_insecure_port("[::]:50051")
print("🚀 NotificationService running on port 50051")
server.start()
server.wait_for_termination()
