import grpc
from autogenerated import services_pb2
from autogenerated import services_pb2_grpc


def call_notification_service(request):
    try:
        with grpc.insecure_channel("localhost:50051") as channel:
            stub = services_pb2_grpc.NotificationServiceStub(channel)

            print("➡️ Calling NotificationService")
            response = stub.SendLoginNotification(
                request,
                timeout=2.0
            )

            print("⬅️ NotificationService response received")
            return response

    except grpc.RpcError as e:
        print("❌ NotificationService RPC failed")
        print(f"   code   : {e.code()}")
        print(f"   details: {e.details()}")

        return services_pb2.ServiceResponse(
            success=False,
            message="Notification service failed"
        )


def call_audit_service(request):
    try:
        with grpc.insecure_channel("localhost:50052") as channel:
            stub = services_pb2_grpc.AuditServiceStub(channel)

            print("➡️ Calling AuditService")
            response = stub.LogLoginEvent(
                request,
                timeout=2.0
            )

            print("⬅️ AuditService response received")
            return response

    except grpc.RpcError as e:
        print("❌ AuditService RPC failed")
        print(f"   code   : {e.code()}")
        print(f"   details: {e.details()}")

        return services_pb2.ServiceResponse(
            success=False,
            message="Audit service failed"
        )
    

def call_profile_service(request):
    try:
        with grpc.insecure_channel("localhost:50053") as channel:
            stub = services_pb2_grpc.ProfileServiceStub(channel)

            print("➡️ Calling ProfileService (Node.js)")
            response = stub.CreateLoginProfile(
                request,
                timeout=2.0
            )

            print("⬅️ ProfileService response received")
            return response

    except grpc.RpcError as e:
        print("❌ ProfileService RPC failed")
        print(f"   code   : {e.code()}")
        print(f"   details: {e.details()}")

        return services_pb2.ServiceResponse(
            success=False,
            message="Profile service failed"
        )



def login_user(user_id, username):
    print("\n🔐 AuthService: User login started")

    request = services_pb2.LoginRequest(
        user_id=user_id,
        username=username
    )

    notif_response = call_notification_service(request)
    print(f"📩 Notification result: {notif_response.message}")

    audit_response = call_audit_service(request)
    print(f"🧾 Audit result: {audit_response.message}")

    profile_response = call_profile_service(request)
    print(f"🧑 Profile result: {profile_response.message}")

    print("✅ AuthService: Login flow completed\n")


if __name__ == "__main__":
    login_user(101, "raja")
