import grpc
from concurrent import futures
from autogenerated import services_pb2
from autogenerated import services_pb2_grpc
import time

class AuditService(
    services_pb2_grpc.AuditServiceServicer
):
    def LogLoginEvent(self, request, context):
        # time.sleep(5)
        print("🧾 AuditService received request")
        print(f"   user_id: {request.user_id}")
        print(f"   username: {request.username}")

        response = services_pb2.ServiceResponse(
            success=True,
            message="Login event audited"
        )

        print("🧾 AuditService sending response")
        print(f"   {response}\n")

        return response


server = grpc.server(futures.ThreadPoolExecutor(max_workers=5))
services_pb2_grpc.add_AuditServiceServicer_to_server(
    AuditService(), server
)

server.add_insecure_port("[::]:50052")
print("🚀 AuditService running on port 50052")
server.start()
server.wait_for_termination()
