# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\x08services\"1\n\x0cLoginRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\"3\n\x0fServiceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2a\n\x13NotificationService\x12J\n\x15SendLoginNotification\x12\x16.services.LoginRequest\x1a\x19.services.ServiceResponse2R\n\x0c\x41uditService\x12\x42\n\rLogLoginEvent\x12\x16.services.LoginRequest\x1a\x19.services.ServiceResponse2Y\n\x0eProfileService\x12G\n\x12\x43reateLoginProfile\x12\x16.services.LoginRequest\x1a\x19.services.ServiceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=28
  _globals['_LOGINREQUEST']._serialized_end=77
  _globals['_SERVICERESPONSE']._serialized_start=79
  _globals['_SERVICERESPONSE']._serialized_end=130
  _globals['_NOTIFICATIONSERVICE']._serialized_start=132
  _globals['_NOTIFICATIONSERVICE']._serialized_end=229
  _globals['_AUDITSERVICE']._serialized_start=231
  _globals['_AUDITSERVICE']._serialized_end=313
  _globals['_PROFILESERVICE']._serialized_start=315
  _globals['_PROFILESERVICE']._serialized_end=404
# @@protoc_insertion_point(module_scope)
