# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import services_pb2 as services__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NotificationServiceStub(object):
    """---------- Notification ---------- 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendLoginNotification = channel.unary_unary(
                '/services.NotificationService/SendLoginNotification',
                request_serializer=services__pb2.LoginRequest.SerializeToString,
                response_deserializer=services__pb2.ServiceResponse.FromString,
                _registered_method=True)


class NotificationServiceServicer(object):
    """---------- Notification ---------- 
    """

    def SendLoginNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendLoginNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLoginNotification,
                    request_deserializer=services__pb2.LoginRequest.FromString,
                    response_serializer=services__pb2.ServiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.NotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.NotificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotificationService(object):
    """---------- Notification ---------- 
    """

    @staticmethod
    def SendLoginNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.NotificationService/SendLoginNotification',
            services__pb2.LoginRequest.SerializeToString,
            services__pb2.ServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AuditServiceStub(object):
    """---------- Audit ---------- 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogLoginEvent = channel.unary_unary(
                '/services.AuditService/LogLoginEvent',
                request_serializer=services__pb2.LoginRequest.SerializeToString,
                response_deserializer=services__pb2.ServiceResponse.FromString,
                _registered_method=True)


class AuditServiceServicer(object):
    """---------- Audit ---------- 
    """

    def LogLoginEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogLoginEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.LogLoginEvent,
                    request_deserializer=services__pb2.LoginRequest.FromString,
                    response_serializer=services__pb2.ServiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.AuditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.AuditService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuditService(object):
    """---------- Audit ---------- 
    """

    @staticmethod
    def LogLoginEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.AuditService/LogLoginEvent',
            services__pb2.LoginRequest.SerializeToString,
            services__pb2.ServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProfileServiceStub(object):
    """---------- Profile ---------- 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateLoginProfile = channel.unary_unary(
                '/services.ProfileService/CreateLoginProfile',
                request_serializer=services__pb2.LoginRequest.SerializeToString,
                response_deserializer=services__pb2.ServiceResponse.FromString,
                _registered_method=True)


class ProfileServiceServicer(object):
    """---------- Profile ---------- 
    """

    def CreateLoginProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateLoginProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLoginProfile,
                    request_deserializer=services__pb2.LoginRequest.FromString,
                    response_serializer=services__pb2.ServiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.ProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.ProfileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProfileService(object):
    """---------- Profile ---------- 
    """

    @staticmethod
    def CreateLoginProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.ProfileService/CreateLoginProfile',
            services__pb2.LoginRequest.SerializeToString,
            services__pb2.ServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
